import React, { createContext, useContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Language = 'en' | 'te' | 'hi';

const STORAGE_KEY = '@hc_buyer_language';

const EN = {
  // ─── Settings modal ───────────────────────────────────────────────
  settings_title:               'App Settings',
  settings_notifications:       'Notifications',
  notif_order_updates:          'Order Status Updates',
  notif_order_updates_desc:     'Placed → dispatched → out for delivery → delivered',
  notif_price_drops:            'Price Drop Alerts',
  notif_price_drops_desc:       'Alert when a wishlist item drops in price',
  notif_new_arrivals:           'New Arrivals Nearby',
  notif_new_arrivals_desc:      'Fresh products from sellers in your area',
  notif_promos:                 'Offers & Promotions',
  notif_promos_desc:            'Discounts, cashback, and seasonal deals',
  settings_display:             'Display',
  display_language:             'Language',
  display_dark_mode:            'Appearance',
  display_dark_mode_desc:       'Choose your preferred theme',
  theme_light:                  'Light',
  theme_dark:                   'Dark',
  theme_system:                 'System',
  settings_shopping:            'Shopping Preferences',
  shop_wallet_auto:             'Auto-apply Harvest Wallet',
  shop_wallet_auto_desc:        'Automatically use wallet balance at checkout',
  shop_gst_inclusive:           'Show GST-inclusive Prices',
  shop_gst_inclusive_desc:      'Display final price including all taxes',
  settings_privacy:             'Privacy & Legal',
  privacy_policy:               'Privacy Policy',
  terms_of_service:             'Terms of Service',
  data_permissions:             'Data & Permissions',
  settings_about:               'About',
  about_version:                'App Version',
  about_rate_app:               'Rate HarvestConnect',
  about_rate_app_desc:          'Enjoying the app? Leave us a review',

  // ─── Help & Support ───────────────────────────────────────────────
  help_title:                   'Help & Support',
  help_hint:                    'Common questions answered below. Tap any question to expand.',
  help_faqs:                    'Frequently Asked Questions',
  help_faq_q1:                  'How do I track my order?',
  help_faq_a1:                  'Go to Orders tab → tap your order → you\'ll see real-time status from seller dispatch to doorstep delivery.',
  help_faq_q2:                  'How do I cancel an order?',
  help_faq_a2:                  'You can cancel before the seller dispatches. Go to Orders → tap the order → tap Cancel. Once dispatched, contact support.',
  help_faq_q3:                  'What payment methods are accepted?',
  help_faq_a3:                  'We accept UPI (GPay, PhonePe, Paytm), debit/credit cards, and Harvest Wallet balance.',
  help_faq_q4:                  'How does Harvest Wallet work?',
  help_faq_a4:                  'Wallet is credited from refunds and referral rewards. It can be used at checkout to pay part or full order value.',
  help_faq_q5:                  'How do I request a refund?',
  help_faq_a5:                  'If you received wrong or damaged goods, raise a return request within 24 hours of delivery via Orders → Issue with Order. Refund is processed in 3–5 business days.',
  help_faq_q6:                  'Can I change my delivery address after ordering?',
  help_faq_a6:                  'Address changes are possible before the seller accepts the order. Contact support immediately on WhatsApp for fastest resolution.',
  help_faq_q7:                  'Which areas does HarvestConnect deliver to?',
  help_faq_a7:                  'We currently serve mandals across Nizamabad, Armoor, Banswada, Kamareddy, and surrounding districts. Coverage is expanding.',
  help_faq_q8:                  'How do I contact the seller directly?',
  help_faq_a8:                  'Once your order is confirmed, the seller\'s contact details appear on the Order Details screen.',
  help_contact:                 'Contact Support',
  help_call:                    'Call Us',
  help_call_hours:              'Mon–Sat, 9 AM – 6 PM',
  help_whatsapp:                'WhatsApp',
  help_whatsapp_sub:            'Fastest response',
  help_email:                   'Email',
  help_email_sub:               'Reply within 24 hrs',
  help_guide:                   'Buyer Guide',
  help_guide_sub:               'Tips for ordering, tracking, and getting the best deals',

  // ─── Home screen ──────────────────────────────────────────────────
  home_brand_name:              'Harvest Connect',
  home_tagline:                 'Local Treasures, Delivered',
  home_search_placeholder:      'Search vegetables, handlooms, spices...',
  home_delivering_to:           'Delivering to',
  home_trust_title:             'Verified Local Vendors',
  home_trust_sub:               'Government ID & Quality Checked',
  home_trust_count:             '2,340+',
  home_shop_by_category:        'Shop by Category',
  home_view_all:                'View All ›',
  home_near_mandal:             'Near Your Mandal',
  home_see_all:                 'See All ›',
  home_featured_products:       'Featured Products',
  home_visit_shop:              'Visit Shop →',
  home_items:                   'items',
  home_banner_badge:            'Telangana Special',
  home_banner_title:            'Discover Authentic\nTelangana Crafts',
  home_banner_sub:              'Bidri work, Nirmal paintings & more',
  home_banner_btn:              'Explore Now →',

  // ─── Explore screen ───────────────────────────────────────────────
  explore_title:                'Explore Products',
  explore_search_placeholder:   'Search products, vendors...',
  explore_region_label:         'Shop by Region',
  explore_sort_by:              'Sort by ▾',
  explore_loading:              'Loading products…',
  explore_products_in:          'products in',
  explore_empty_title:          'No products in this region yet',
  explore_empty_sub:            'Vendors are joining — check another region or come back soon!',
  explore_hyperlocal:           'Hyperlocal',
  explore_district:             'District',
  explore_state:                'State',
  explore_nationwide:           'Nationwide',
  explore_nearby:               'Nearby',
  explore_all_india:            'All India',

  // ─── Cart screen ──────────────────────────────────────────────────
  cart_title:                   'Shopping Cart',
  cart_empty_title:             'Your cart is empty',
  cart_empty_desc:              'Add products from Home or Explore to get started.',
  cart_delivering_to:           'Delivering to',
  cart_change:                  'Change ›',
  cart_no_address:              'Tap to add a delivery address',
  cart_select_all:              'Select All',
  cart_deselect_all:            'Deselect All',
  cart_selected_of:             'of',
  cart_selected:                'selected',
  cart_coupon_placeholder:      'Enter coupon code',
  cart_apply:                   'Apply',
  cart_price_details:           'Price Details',
  cart_subtotal:                'Subtotal',
  cart_delivery_fee:            'Delivery Fee',
  cart_coupon_discount:         'Coupon Discount',
  cart_total_payable:           'Total Payable',
  cart_select_to_continue:      'Select items to continue',
  cart_proceed_checkout:        'Proceed to Checkout  →',
  cart_terms:                   'By placing order, you agree to our Terms & Conditions',

  // ─── Orders screen ────────────────────────────────────────────────
  orders_title:                 'My Orders',
  orders_subtitle:              'Track your purchases',
  orders_tab_all:               'All',
  orders_tab_active:            'Active',
  orders_tab_delivered:         'Delivered',
  orders_tab_cancelled:         'Cancelled',
  orders_empty_title:           'No orders here yet',
  orders_empty_sub_all:         "You haven't placed any orders yet. Start exploring!",
  orders_empty_sub_filter:      'orders will appear here.',
  orders_status_delivered:      'Delivered',
  orders_status_transit:        'In Transit',
  orders_status_processing:     'Processing',
  orders_status_cancelled:      'Cancelled',
  orders_expected_by:           'Expected by',
  orders_total:                 'Order Total',
  orders_support:               '💬 Support',
  orders_track:                 'Track →',

  // ─── Profile screen ───────────────────────────────────────────────
  profile_loading:              'Loading profile…',
  profile_member_since:         'Member since',
  profile_orders:               'Orders',
  profile_wishlist:             'Wishlist',
  profile_wallet:               'Wallet',
  profile_in_cart:              'In Cart',
  profile_location_title:       'Your Location',
  profile_detect:               '⟳ Detect',
  profile_detecting:            '…',
  profile_open_settings:        'Open Settings →',
  profile_manual_placeholder:   'Type your area or city…',
  profile_save:                 'Save',
  profile_sign_out:             '🚪  Sign Out',
  profile_total:                'total',
  profile_items:                'items',

  // Profile menu items
  menu_my_orders:               'My Orders',
  menu_my_orders_desc:          'Track your purchases',
  menu_wishlist:                'Wishlist',
  menu_wishlist_desc:           'Your saved items',
  menu_saved_addresses:         'Saved Addresses',
  menu_saved_addresses_desc:    'Manage delivery locations',
  menu_payment_methods:         'Payment Methods',
  menu_payment_methods_desc:    'Cards & UPI',
  menu_wallet:                  'Harvest Wallet',
  menu_wallet_desc:             'Your balance',
  menu_refer_earn:              'Refer & Earn',
  menu_refer_earn_desc:         'Get ₹100 per referral',
  menu_become_seller:           'Become a Seller',
  menu_become_seller_desc:      'Start your local business',
  menu_settings:                'Settings',
  menu_settings_desc:           'App preferences',
  menu_help:                    'Help & Support',
  menu_help_desc:               'FAQs and contact',

  // ─── Login screen ─────────────────────────────────────────────────
  login_app_name:               'Harvest Connect',
  login_hero_tagline:           'Farm fresh, straight to your door',
  login_welcome:                'Welcome back 👋',
  login_card_sub:               'Enter your phone number to continue',
  login_secure_otp:             '🔒  Secure OTP',
  login_instant:                '⚡  Instant login',
  login_phone_label:            'Mobile number',
  login_phone_placeholder:      '+91 XXXXX XXXXX',
  login_send_otp:               'Send OTP  →',
  login_new_to:                 'New to HarvestConnect?',
  login_create_account:         'Create an account',
  login_trusted_by:             'Trusted by',
  login_trusted_suffix:         'buyers across Telangana',

  // ─── OTP screen ───────────────────────────────────────────────────
  otp_heading:                  'Verify your number',
  otp_sub:                      'We sent a 6-digit code to',
  otp_verifying:                'Verifying…',
  otp_resend:                   'Resend OTP',
  otp_resend_in:                'Resend OTP in',
  otp_badge_register:           '🆕  Registration OTP',
  otp_badge_login:              '🔐  Login OTP',
  otp_tip_register:             '💡  If you added an email, check your inbox too — we sent the code there as well',
  otp_tip_login:                "💡  Didn't get it? Check SMS and wait a moment before resending",
  otp_back:                     'Back',

  // ─── Register screen ──────────────────────────────────────────────
  register_hero_tagline:        'Connect with local farmers & artisans',
  register_benefit_free:        'Free to join',
  register_benefit_local:       'Verified local',
  register_benefit_delivery:    'Fast delivery',
  register_title:               'Create account',
  register_sub:                 'Join 2,340+ buyers. Takes less than a minute.',
  register_name_label:          'Full name',
  register_name_placeholder:    'Enter your full name',
  register_phone_label:         'Mobile number',
  register_email_label:         'Email',
  register_email_optional:      'optional · for OTP delivery',
  register_referral_label:      'Referral code',
  register_referral_optional:   'optional · get ₹50 off first order',
  register_create_btn:          'Create Account  →',
  register_note:                '📲  We\'ll send a 6-digit OTP to verify your mobile number',
  register_already:             'Already a member?',
  register_login_instead:       'Log in instead',

  // ─── Checkout screen ──────────────────────────────────────────────
  checkout_title:               'Checkout',
  checkout_back:                '← Back',
  checkout_deliver_to:          'Deliver To',
  checkout_delivery_slot:       'Delivery Slot',
  checkout_payment_method:      'Payment Method',
  checkout_order_summary:       'Order Summary',
  checkout_change:              'Change ›',
  checkout_default:             'Default',
  checkout_subtotal:            'Subtotal',
  checkout_delivery_fee:        'Delivery Fee',
  checkout_coupon_discount:     'Coupon Discount',
  checkout_total:               'Total Payable',
  checkout_place_order:         'Place Order',
  checkout_items_from:          'items from',
  checkout_vendor:              'vendor',
  checkout_vendors:             'vendors',
  checkout_slot_today:          'Today',
  checkout_slot_today_sub:      '4 PM – 6 PM',
  checkout_slot_tomorrow:       'Tomorrow',
  checkout_slot_tomorrow_sub:   'Before 12 PM',
  checkout_slot_schedule:       'Schedule',
  checkout_slot_schedule_sub:   'Pick a date',
  checkout_cod:                 'Pay when delivered',
  checkout_wallet_empty:        'No balance — add money first',
  checkout_please_login:        'Please log in to continue.',

  // ─── Order Confirmed screen ────────────────────────────────────────
  order_confirmed_title:        'Order Placed! 🎉',
  order_confirmed_sub:          'Your order has been placed successfully.',
  order_confirmed_id:           'Order ID',
  order_confirmed_slot:         'Delivery Slot',
  order_confirmed_payment:      'Payment',
  order_confirmed_track:        'Track My Order',
  order_confirmed_continue:     'Continue Shopping',

  // ─── Order Detail screen ──────────────────────────────────────────
  order_detail_title:           'Order Details',
  order_detail_back:            '← Back',
  order_detail_timeline:        'Order Timeline',
  order_detail_placed:          'Order Placed',
  order_detail_confirmed:       'Confirmed',
  order_detail_dispatched:      'Dispatched',
  order_detail_transit:         'In Transit',
  order_detail_delivered:       'Delivered',
  order_detail_items:           'Items',
  order_detail_summary:         'Price Summary',
  order_detail_subtotal:        'Subtotal',
  order_detail_delivery:        'Delivery Fee',
  order_detail_discount:        'Discount',
  order_detail_total:           'Total Paid',

  // ─── Product Detail screen ────────────────────────────────────────
  product_back:                 '← Back',
  product_add_to_cart:          'Add to Cart',
  product_add_more:             '+ Add More',
  product_in_cart:              'in cart',
  product_about:                'About this product',
  product_vendor:               'Sold by',
  product_visit_shop:           'Visit Shop →',
  product_rating:               'Rating & Reviews',

  // ─── Vendor screen ────────────────────────────────────────────────
  vendor_back:                  '← Back',
  vendor_products:              'Products',
  vendor_rating:                'Rating',
  vendor_distance:              'Distance',
  vendor_items:                 'items',
  vendor_empty:                 'No products from this vendor yet',

  // ─── Category screen ──────────────────────────────────────────────
  category_back:                '← Back',
  category_products:            'Products',
  category_empty:               'No products in this category yet',
  category_empty_sub:           'Check back soon — vendors are adding products!',

  // ─── Address Book screen ──────────────────────────────────────────
  address_book_title:           'Saved Addresses',
  address_select_title:         'Select Address',
  address_back:                 '← Back',
  address_empty_title:          'No addresses saved',
  address_empty_sub:            'Add a delivery address to get started.',
  address_add:                  '+ Add New Address',
  address_default:              'Default',
  address_set_default:          'Set as Default',
  address_edit:                 'Edit',
  address_delete:               'Delete',
  address_cannot_delete_title:  'Cannot Delete',
  address_cannot_delete_msg:    'You need at least one delivery address. Add a new address first, then delete this one.',
  address_delete_title:         'Delete Address',
  address_delete_confirm:       'Remove',
  address_cancel:               'Cancel',
  address_ok:                   'OK',

  // ─── Address Form screen ──────────────────────────────────────────
  address_form_title_add:       'Add Address',
  address_form_title_edit:      'Edit Address',
  address_form_name:            'Full Name',
  address_form_phone:           'Phone Number',
  address_form_line1:           'Address Line 1',
  address_form_line2:           'Address Line 2 (optional)',
  address_form_city:            'City / Town',
  address_form_district:        'District',
  address_form_state:           'State',
  address_form_pincode:         'Pincode',
  address_form_label:           'Label',
  address_form_save:            'Save Address',
  address_form_update:          'Update Address',

  // ─── Favorites screen ─────────────────────────────────────────────
  favorites_title:              'My Wishlist',
  favorites_loading:            'Loading…',
  favorites_empty_title:        'Your wishlist is empty',
  favorites_empty_sub:          'Tap the heart icon on any product to save it here',
  favorites_explore:            'Explore Products →',
  favorites_item:               'item',
  favorites_items:              'items',

  // ─── Location Picker screen ───────────────────────────────────────
  location_title:               'Choose Location',
  location_search_placeholder:  'Search for your area or pincode…',
  location_detecting:           'Detecting your location…',
  location_detect_gps:          'Use Current Location',
  location_suggestions:         'Suggestions',
  location_recent:              'Recent',
  location_select:              'Select',

  // ─── Payments screen ──────────────────────────────────────────────
  payments_title:               'Payment Methods',
  payments_back:                '← Back',
  payments_upi_section:         'UPI IDs',
  payments_card_section:        'Cards',
  payments_add_upi:             'Add UPI ID',
  payments_add_card:            'Add Card',
  payments_no_upi:              'No UPI IDs saved',
  payments_no_cards:            'No cards saved',
  payments_default:             'Default',
  payments_set_default:         'Set Default',
  payments_remove:              'Remove',

  // ─── Wallet screen ────────────────────────────────────────────────
  wallet_title:                 'Harvest Wallet',
  wallet_back:                  '← Back',
  wallet_balance_label:         'Available Balance',
  wallet_balance_sub:           'Use at checkout for instant payment',
  wallet_add_money:             '+ Add Money',
  wallet_form_title:            'Add Money to Wallet',
  wallet_select_amount:         'Select Amount',
  wallet_custom_or:             '— or enter custom amount —',
  wallet_pay_via:               'Pay via',
  wallet_no_pm:                 'No payment methods saved — tap to add UPI or card',
  wallet_cancel:                'Cancel',
  wallet_confirm_add:           'Add',
  wallet_preview_adding:        'Adding',
  wallet_preview_to:            'to wallet',
  wallet_preview_new_bal:       'New balance will be',
  wallet_transactions:          'Transaction History',
  wallet_empty:                 'No transactions yet',
  wallet_empty_sub:             'Add money to get started',
  wallet_info:                  'Wallet balance can be used at checkout. Maximum wallet balance is ₹10,000. Unused balance never expires.',
  wallet_added_title:           'Money Added!',
  wallet_added_msg:             'added to your Harvest Wallet.',
  wallet_min_error:             'Minimum add amount is ₹1',
  wallet_max_error:             'Maximum is ₹10,000 per transaction',
  wallet_pm_error:              'Choose a payment method',

  // ─── Referral screen ──────────────────────────────────────────────
  referral_title:               'Refer & Earn',
  referral_back:                '←',
  referral_hero_title:          'Invite friends,\nearn rewards',
  referral_hero_sub:            'You get ₹100 for every friend who places their first order.\nThey get ₹50 off their first order instantly.',
  referral_code_label:          'Your referral code',
  referral_copy:                'Copy',
  referral_copied:              '✓ Copied',
  referral_share:               'Share with friends  ↗',
  referral_friends_invited:     'Friends Invited',
  referral_orders_placed:       'Orders Placed',
  referral_total_earned:        'Total Earned',
  referral_your_referrals:      'Your referrals',
  referral_rewarded:            'Friend placed first order',
  referral_awaiting:            'Friend signed up — awaiting first order',
  referral_pending:             'Pending',
  referral_how_title:           'How it works',
  referral_step1_title:         'Share your code',
  referral_step1_desc:          'Send your unique code to friends via WhatsApp, SMS, or any app.',
  referral_step2_title:         'Friend signs up',
  referral_step2_desc:          'They enter your code at registration and get ₹50 off instantly.',
  referral_step3_title:         'Friend places first order',
  referral_step3_desc:          'Once their first order is delivered, ₹100 is credited to your Harvest Wallet.',
  referral_terms_1:             'Referral reward credited after friend\'s first delivered order',
  referral_terms_2:             'Friend must be a new user (never registered before)',
  referral_terms_3:             'One referral code per account',
  referral_terms_4:             'Maximum 10 referrals per month per user',

  // ─── Search screen ────────────────────────────────────────────────
  search_placeholder:           'Search vegetables, handlooms, spices...',
  search_results:               'Results for',
  search_result_count:          'products found',
  search_no_results:            'No results found',
  search_no_results_sub:        'Try a different keyword or browse categories',
  search_recent:                'Recent Searches',
  search_clear:                 'Clear',

  // ─── Vendors screen ───────────────────────────────────────────────
  vendors_title:                'Local Vendors',
  vendors_back:                 '← Back',
  vendors_count:                'vendors nearby',
  vendors_empty:                'No vendors found in your area',
  vendors_empty_sub:            'Try expanding your search area',
  vendors_visit:                'Visit Shop →',
};

const TE: typeof EN = {
  // ─── Settings modal ───────────────────────────────────────────────
  settings_title:               'యాప్ సెట్టింగ్‌లు',
  settings_notifications:       'నోటిఫికేషన్లు',
  notif_order_updates:          'ఆర్డర్ స్థితి అప్‌డేట్లు',
  notif_order_updates_desc:     'ఆర్డర్ పెట్టబడింది → పంపబడింది → డెలివరీలో ఉంది → అందింది',
  notif_price_drops:            'ధర తగ్గింపు హెచ్చరికలు',
  notif_price_drops_desc:       'విష్‌లిస్ట్ వస్తువు ధర తగ్గినప్పుడు తెలపండి',
  notif_new_arrivals:           'దగ్గర్లో కొత్త వస్తువులు',
  notif_new_arrivals_desc:      'మీ ప్రాంతంలోని విక్రేతల నుండి తాజా ఉత్పత్తులు',
  notif_promos:                 'ఆఫర్లు & ప్రమోషన్లు',
  notif_promos_desc:            'తగ్గింపులు, క్యాష్‌బ్యాక్ మరియు సీజనల్ డీల్స్',
  settings_display:             'డిస్‌ప్లే',
  display_language:             'భాష',
  display_dark_mode:            'రూపం',
  display_dark_mode_desc:       'మీకు నచ్చిన థీమ్ ఎంచుకోండి',
  theme_light:                  'వెలుతురు',
  theme_dark:                   'చీకటి',
  theme_system:                 'సిస్టమ్',
  settings_shopping:            'షాపింగ్ ప్రాధాన్యతలు',
  shop_wallet_auto:             'వాలెట్ స్వయంచాలకంగా వర్తించు',
  shop_wallet_auto_desc:        'చెక్‌అవుట్‌లో వాలెట్ బ్యాలెన్స్ స్వయంచాలకంగా ఉపయోగించు',
  shop_gst_inclusive:           'GST తో ధర చూపించు',
  shop_gst_inclusive_desc:      'అన్ని పన్నులతో సహా తుది ధర చూపించు',
  settings_privacy:             'గోప్యత & చట్టపరమైనది',
  privacy_policy:               'గోప్యతా విధానం',
  terms_of_service:             'సేవా నిబంధనలు',
  data_permissions:             'డేటా & అనుమతులు',
  settings_about:               'గురించి',
  about_version:                'యాప్ వెర్షన్',
  about_rate_app:               'HarvestConnect రేట్ చేయండి',
  about_rate_app_desc:          'యాప్ నచ్చిందా? మాకు రివ్యూ ఇవ్వండి',

  // ─── Help & Support ───────────────────────────────────────────────
  help_title:                   'సహాయం & మద్దతు',
  help_hint:                    'సాధారణ ప్రశ్నలు క్రింద ఉన్నాయి. విస్తరించడానికి నొక్కండి.',
  help_faqs:                    'తరచుగా అడిగే ప్రశ్నలు',
  help_faq_q1:                  'నా ఆర్డర్‌ని ఎలా ట్రాక్ చేయాలి?',
  help_faq_a1:                  'Orders టాబ్ → మీ ఆర్డర్ నొక్కండి → విక్రేత పంపించినది నుండి డెలివరీ వరకు రియల్-టైమ్ స్థితి కనిపిస్తుంది.',
  help_faq_q2:                  'ఆర్డర్ ఎలా రద్దు చేయాలి?',
  help_faq_a2:                  'విక్రేత పంపించే ముందు రద్దు చేయవచ్చు. Orders → ఆర్డర్ నొక్కి → Cancel చేయండి.',
  help_faq_q3:                  'ఏ పేమెంట్ పద్ధతులు అందుబాటులో ఉన్నాయి?',
  help_faq_a3:                  'UPI (GPay, PhonePe, Paytm), డెబిట్/క్రెడిట్ కార్డులు మరియు Harvest Wallet స్వీకరిస్తాం.',
  help_faq_q4:                  'Harvest Wallet ఎలా పని చేస్తుంది?',
  help_faq_a4:                  'రీఫండ్లు మరియు రెఫరల్ రివార్డుల నుండి వాలెట్ నిండుతుంది. చెక్‌అవుట్‌లో పూర్తి లేదా పాక్షిక పేమెంట్ చేయవచ్చు.',
  help_faq_q5:                  'రీఫండ్ ఎలా అడగాలి?',
  help_faq_a5:                  'తప్పుడు లేదా దెబ్బతిన్న వస్తువు వస్తే, డెలివరీ తర్వాత 24 గంటల్లో Orders → Issue with Order ద్వారా అభ్యర్థన చేయండి.',
  help_faq_q6:                  'ఆర్డర్ తర్వాత చిరునామా మార్చవచ్చా?',
  help_faq_a6:                  'విక్రేత ఆర్డర్ స్వీకరించే ముందు మార్చవచ్చు. వేగంగా WhatsApp ద్వారా సంప్రదించండి.',
  help_faq_q7:                  'HarvestConnect ఎక్కడ డెలివరీ చేస్తుంది?',
  help_faq_a7:                  'ప్రస్తుతం నిజామాబాద్, ఆర్మూర్, బాన్సువాడ, కామారెడ్డి మరియు చుట్టుపక్కల మండలాలలో సేవలు అందిస్తున్నాం.',
  help_faq_q8:                  'విక్రేతను నేరుగా సంప్రదించడం ఎలా?',
  help_faq_a8:                  'ఆర్డర్ నిర్ధారించబడిన తర్వాత, Order Details స్క్రీన్‌లో విక్రేత సంప్రదింపు వివరాలు కనిపిస్తాయి.',
  help_contact:                 'మద్దతు సంప్రదించండి',
  help_call:                    'కాల్ చేయండి',
  help_call_hours:              'సోమ–శని, ఉ. 9 – సా. 6',
  help_whatsapp:                'WhatsApp',
  help_whatsapp_sub:            'వేగవంతమైన సమాధానం',
  help_email:                   'ఇమెయిల్',
  help_email_sub:               '24 గంటల్లో సమాధానం',
  help_guide:                   'కొనుగోలుదారు గైడ్',
  help_guide_sub:               'ఆర్డర్లు, ట్రాకింగ్ మరియు మంచి డీల్స్ కోసం చిట్కాలు',

  // ─── Home screen ──────────────────────────────────────────────────
  home_brand_name:              'Harvest Connect',
  home_tagline:                 'స్థానిక నిధులు, డెలివరీతో',
  home_search_placeholder:      'కూరగాయలు, చేనేత, మసాలాలు వెతకండి...',
  home_delivering_to:           'డెలివరీ చేస్తున్నాం',
  home_trust_title:             'ధృవీకరించబడిన స్థానిక విక్రేతలు',
  home_trust_sub:               'ప్రభుత్వ ID & నాణ్యత తనిఖీ చేయబడింది',
  home_trust_count:             '2,340+',
  home_shop_by_category:        'వర్గం ద్వారా షాపింగ్',
  home_view_all:                'అన్నీ చూడు ›',
  home_near_mandal:             'మీ మండలం దగ్గర',
  home_see_all:                 'అన్నీ చూడు ›',
  home_featured_products:       'ఫీచర్డ్ ఉత్పత్తులు',
  home_visit_shop:              'షాప్ సందర్శించండి →',
  home_items:                   'వస్తువులు',
  home_banner_badge:            'తెలంగాణ స్పెషల్',
  home_banner_title:            'అసలైన తెలంగాణ\nకళాఖండాలు కనుగొనండి',
  home_banner_sub:              'బిద్రీ పని, నిర్మల్ చిత్రలేఖనాలు & మరిన్ని',
  home_banner_btn:              'ఇప్పుడే చూడండి →',

  // ─── Explore screen ───────────────────────────────────────────────
  explore_title:                'ఉత్పత్తులు అన్వేషించండి',
  explore_search_placeholder:   'ఉత్పత్తులు, విక్రేతలు వెతకండి...',
  explore_region_label:         'ప్రాంతం ద్వారా షాపింగ్',
  explore_sort_by:              'క్రమబద్ధీకరించు ▾',
  explore_loading:              'లోడ్ అవుతోంది…',
  explore_products_in:          'ఉత్పత్తులు',
  explore_empty_title:          'ఈ ప్రాంతంలో ఇంకా ఉత్పత్తులు లేవు',
  explore_empty_sub:            'విక్రేతలు చేరుతున్నారు — మరొక ప్రాంతం చూడండి లేదా తర్వాత రండి!',
  explore_hyperlocal:           'హైపర్‌లోకల్',
  explore_district:             'జిల్లా',
  explore_state:                'రాష్ట్రం',
  explore_nationwide:           'దేశవ్యాప్తం',
  explore_nearby:               'దగ్గర',
  explore_all_india:            'అఖిల భారతం',

  // ─── Cart screen ──────────────────────────────────────────────────
  cart_title:                   'షాపింగ్ కార్ట్',
  cart_empty_title:             'మీ కార్ట్ ఖాళీగా ఉంది',
  cart_empty_desc:              'ప్రారంభించడానికి హోమ్ లేదా Explore నుండి ఉత్పత్తులు జోడించండి.',
  cart_delivering_to:           'డెలివరీ చేస్తున్నాం',
  cart_change:                  'మార్చు ›',
  cart_no_address:              'డెలివరీ చిరునామా జోడించడానికి నొక్కండి',
  cart_select_all:              'అన్నీ ఎంచుకో',
  cart_deselect_all:            'అన్నీ తీసివేయి',
  cart_selected_of:             'లో',
  cart_selected:                'ఎంచుకోబడింది',
  cart_coupon_placeholder:      'కూపన్ కోడ్ నమోదు చేయండి',
  cart_apply:                   'వర్తించు',
  cart_price_details:           'ధర వివరాలు',
  cart_subtotal:                'సబ్ టోటల్',
  cart_delivery_fee:            'డెలివరీ రుసుము',
  cart_coupon_discount:         'కూపన్ తగ్గింపు',
  cart_total_payable:           'చెల్లించాల్సిన మొత్తం',
  cart_select_to_continue:      'కొనసాగించడానికి వస్తువులు ఎంచుకోండి',
  cart_proceed_checkout:        'చెక్‌అవుట్‌కు వెళ్ళండి →',
  cart_terms:                   'ఆర్డర్ పెట్టడం ద్వారా, మీరు మా నిబంధనలకు అంగీకరిస్తున్నారు',

  // ─── Orders screen ────────────────────────────────────────────────
  orders_title:                 'నా ఆర్డర్లు',
  orders_subtitle:              'మీ కొనుగోళ్ళను ట్రాక్ చేయండి',
  orders_tab_all:               'అన్నీ',
  orders_tab_active:            'చురుకైనవి',
  orders_tab_delivered:         'అందినవి',
  orders_tab_cancelled:         'రద్దు చేయబడినవి',
  orders_empty_title:           'ఇంకా ఆర్డర్లు లేవు',
  orders_empty_sub_all:         'మీరు ఇంకా ఆర్డర్లు పెట్టలేదు. అన్వేషించడం ప్రారంభించండి!',
  orders_empty_sub_filter:      'ఆర్డర్లు ఇక్కడ కనిపిస్తాయి.',
  orders_status_delivered:      'అందింది',
  orders_status_transit:        'మార్గంలో ఉంది',
  orders_status_processing:     'ప్రాసెసింగ్',
  orders_status_cancelled:      'రద్దు చేయబడింది',
  orders_expected_by:           'ఆశించిన తేదీ',
  orders_total:                 'ఆర్డర్ మొత్తం',
  orders_support:               '💬 సహాయం',
  orders_track:                 'ట్రాక్ →',

  // ─── Profile screen ───────────────────────────────────────────────
  profile_loading:              'ప్రొఫైల్ లోడ్ అవుతోంది…',
  profile_member_since:         'సభ్యుడు నుండి',
  profile_orders:               'ఆర్డర్లు',
  profile_wishlist:             'విష్‌లిస్ట్',
  profile_wallet:               'వాలెట్',
  profile_in_cart:              'కార్ట్‌లో',
  profile_location_title:       'మీ స్థానం',
  profile_detect:               '⟳ గుర్తించు',
  profile_detecting:            '…',
  profile_open_settings:        'సెట్టింగ్‌లు తెరవండి →',
  profile_manual_placeholder:   'మీ ప్రాంతం లేదా నగరం నమోదు చేయండి…',
  profile_save:                 'సేవ్ చేయి',
  profile_sign_out:             '🚪  సైన్ అవుట్',
  profile_total:                'మొత్తం',
  profile_items:                'వస్తువులు',

  menu_my_orders:               'నా ఆర్డర్లు',
  menu_my_orders_desc:          'మీ కొనుగోళ్ళను ట్రాక్ చేయండి',
  menu_wishlist:                'విష్‌లిస్ట్',
  menu_wishlist_desc:           'మీరు సేవ్ చేసిన వస్తువులు',
  menu_saved_addresses:         'సేవ్ చేసిన చిరునామాలు',
  menu_saved_addresses_desc:    'డెలివరీ స్థానాలు నిర్వహించండి',
  menu_payment_methods:         'పేమెంట్ పద్ధతులు',
  menu_payment_methods_desc:    'కార్డులు & UPI',
  menu_wallet:                  'హార్వెస్ట్ వాలెట్',
  menu_wallet_desc:             'మీ బ్యాలెన్స్',
  menu_refer_earn:              'రెఫర్ & సంపాదించండి',
  menu_refer_earn_desc:         'ప్రతి రెఫరల్‌కు ₹100 పొందండి',
  menu_become_seller:           'విక్రేత అవ్వండి',
  menu_become_seller_desc:      'మీ స్థానిక వ్యాపారం ప్రారంభించండి',
  menu_settings:                'సెట్టింగ్‌లు',
  menu_settings_desc:           'యాప్ ప్రాధాన్యతలు',
  menu_help:                    'సహాయం & మద్దతు',
  menu_help_desc:               'FAQs మరియు సంప్రదింపు',

  // ─── Login screen ─────────────────────────────────────────────────
  login_app_name:               'Harvest Connect',
  login_hero_tagline:           'తాజా పంట, నేరుగా మీ తలుపుకు',
  login_welcome:                'తిరిగి స్వాగతం 👋',
  login_card_sub:               'కొనసాగించడానికి మీ ఫోన్ నంబర్ నమోదు చేయండి',
  login_secure_otp:             '🔒  సురక్షిత OTP',
  login_instant:                '⚡  తక్షణ లాగిన్',
  login_phone_label:            'మొబైల్ నంబర్',
  login_phone_placeholder:      '+91 XXXXX XXXXX',
  login_send_otp:               'OTP పంపండి →',
  login_new_to:                 'HarvestConnect కొత్తా?',
  login_create_account:         'ఖాతా సృష్టించండి',
  login_trusted_by:             'విశ్వసించబడింది',
  login_trusted_suffix:         'తెలంగాణలో కొనుగోలుదారులు',

  // ─── OTP screen ───────────────────────────────────────────────────
  otp_heading:                  'మీ నంబర్ ధృవీకరించండి',
  otp_sub:                      '6-అంకె కోడ్ పంపబడింది',
  otp_verifying:                'ధృవీకరిస్తోంది…',
  otp_resend:                   'OTP మళ్ళీ పంపండి',
  otp_resend_in:                'OTP మళ్ళీ పంపండి',
  otp_badge_register:           '🆕  రిజిస్ట్రేషన్ OTP',
  otp_badge_login:              '🔐  లాగిన్ OTP',
  otp_tip_register:             '💡  ఇమెయిల్ జోడించినట్లయితే, మీ ఇన్‌బాక్స్ కూడా చూడండి',
  otp_tip_login:                '💡  రాలేదా? SMS చూడండి మరియు మళ్ళీ పంపే ముందు కొంచెం ఆగండి',
  otp_back:                     'వెనక్కి',

  // ─── Register screen ──────────────────────────────────────────────
  register_hero_tagline:        'స్థానిక రైతులు & కళాకారులతో కనెక్ట్ అవ్వండి',
  register_benefit_free:        'ఉచిత సభ్యత్వం',
  register_benefit_local:       'ధృవీకరించబడిన స్థానికం',
  register_benefit_delivery:    'వేగవంతమైన డెలివరీ',
  register_title:               'ఖాతా సృష్టించండి',
  register_sub:                 '2,340+ కొనుగోలుదారులతో చేరండి. ఒక నిమిషం కంటే తక్కువ.',
  register_name_label:          'పూర్తి పేరు',
  register_name_placeholder:    'మీ పూర్తి పేరు నమోదు చేయండి',
  register_phone_label:         'మొబైల్ నంబర్',
  register_email_label:         'ఇమెయిల్',
  register_email_optional:      'ఐచ్ఛికం · OTP డెలివరీ కోసం',
  register_referral_label:      'రెఫరల్ కోడ్',
  register_referral_optional:   'ఐచ్ఛికం · మొదటి ఆర్డర్‌పై ₹50 తగ్గింపు',
  register_create_btn:          'ఖాతా సృష్టించండి →',
  register_note:                '📲  మీ మొబైల్ నంబర్ ధృవీకరించడానికి 6-అంకె OTP పంపుతాం',
  register_already:             'ఇప్పటికే సభ్యుడా?',
  register_login_instead:       'లాగిన్ చేయండి',

  // ─── Checkout screen ──────────────────────────────────────────────
  checkout_title:               'చెక్‌అవుట్',
  checkout_back:                '← వెనక్కి',
  checkout_deliver_to:          'డెలివరీ చేయడానికి',
  checkout_delivery_slot:       'డెలివరీ స్లాట్',
  checkout_payment_method:      'పేమెంట్ పద్ధతి',
  checkout_order_summary:       'ఆర్డర్ సారాంశం',
  checkout_change:              'మార్చు ›',
  checkout_default:             'డిఫాల్ట్',
  checkout_subtotal:            'సబ్ టోటల్',
  checkout_delivery_fee:        'డెలివరీ రుసుము',
  checkout_coupon_discount:     'కూపన్ తగ్గింపు',
  checkout_total:               'చెల్లించాల్సిన మొత్తం',
  checkout_place_order:         'ఆర్డర్ పెట్టండి',
  checkout_items_from:          'వస్తువులు',
  checkout_vendor:              'విక్రేత',
  checkout_vendors:             'విక్రేతలు',
  checkout_slot_today:          'నేడు',
  checkout_slot_today_sub:      'సా. 4 – 6',
  checkout_slot_tomorrow:       'రేపు',
  checkout_slot_tomorrow_sub:   'మధ్యాహ్నం 12 లోపు',
  checkout_slot_schedule:       'షెడ్యూల్',
  checkout_slot_schedule_sub:   'తేదీ ఎంచుకోండి',
  checkout_cod:                 'అందిన తర్వాత చెల్లించండి',
  checkout_wallet_empty:        'బ్యాలెన్స్ లేదు — ముందు డబ్బు జోడించండి',
  checkout_please_login:        'కొనసాగించడానికి దయచేసి లాగిన్ చేయండి.',

  // ─── Order Confirmed screen ────────────────────────────────────────
  order_confirmed_title:        'ఆర్డర్ పెట్టబడింది! 🎉',
  order_confirmed_sub:          'మీ ఆర్డర్ విజయవంతంగా పెట్టబడింది.',
  order_confirmed_id:           'ఆర్డర్ ID',
  order_confirmed_slot:         'డెలివరీ స్లాట్',
  order_confirmed_payment:      'పేమెంట్',
  order_confirmed_track:        'నా ఆర్డర్ ట్రాక్ చేయి',
  order_confirmed_continue:     'షాపింగ్ కొనసాగించు',

  // ─── Order Detail screen ──────────────────────────────────────────
  order_detail_title:           'ఆర్డర్ వివరాలు',
  order_detail_back:            '← వెనక్కి',
  order_detail_timeline:        'ఆర్డర్ టైమ్‌లైన్',
  order_detail_placed:          'ఆర్డర్ పెట్టబడింది',
  order_detail_confirmed:       'నిర్ధారించబడింది',
  order_detail_dispatched:      'పంపబడింది',
  order_detail_transit:         'మార్గంలో ఉంది',
  order_detail_delivered:       'అందింది',
  order_detail_items:           'వస్తువులు',
  order_detail_summary:         'ధర సారాంశం',
  order_detail_subtotal:        'సబ్ టోటల్',
  order_detail_delivery:        'డెలివరీ రుసుము',
  order_detail_discount:        'తగ్గింపు',
  order_detail_total:           'మొత్తం చెల్లించబడింది',

  // ─── Product Detail screen ────────────────────────────────────────
  product_back:                 '← వెనక్కి',
  product_add_to_cart:          'కార్ట్‌కు జోడించు',
  product_add_more:             '+ మరిన్ని జోడించు',
  product_in_cart:              'కార్ట్‌లో ఉంది',
  product_about:                'ఈ ఉత్పత్తి గురించి',
  product_vendor:               'విక్రయదారు',
  product_visit_shop:           'షాప్ సందర్శించండి →',
  product_rating:               'రేటింగ్ & రివ్యూలు',

  // ─── Vendor screen ────────────────────────────────────────────────
  vendor_back:                  '← వెనక్కి',
  vendor_products:              'ఉత్పత్తులు',
  vendor_rating:                'రేటింగ్',
  vendor_distance:              'దూరం',
  vendor_items:                 'వస్తువులు',
  vendor_empty:                 'ఈ విక్రేత నుండి ఇంకా ఉత్పత్తులు లేవు',

  // ─── Category screen ──────────────────────────────────────────────
  category_back:                '← వెనక్కి',
  category_products:            'ఉత్పత్తులు',
  category_empty:               'ఈ వర్గంలో ఇంకా ఉత్పత్తులు లేవు',
  category_empty_sub:           'త్వరలో చూడండి — విక్రేతలు ఉత్పత్తులు జోడిస్తున్నారు!',

  // ─── Address Book screen ──────────────────────────────────────────
  address_book_title:           'సేవ్ చేసిన చిరునామాలు',
  address_select_title:         'చిరునామా ఎంచుకోండి',
  address_back:                 '← వెనక్కి',
  address_empty_title:          'చిరునామాలు సేవ్ చేయలేదు',
  address_empty_sub:            'ప్రారంభించడానికి డెలివరీ చిరునామా జోడించండి.',
  address_add:                  '+ కొత్త చిరునామా జోడించు',
  address_default:              'డిఫాల్ట్',
  address_set_default:          'డిఫాల్ట్‌గా సెట్ చేయి',
  address_edit:                 'సవరించు',
  address_delete:               'తొలగించు',
  address_cannot_delete_title:  'తొలగించలేరు',
  address_cannot_delete_msg:    'కనీసం ఒక డెలివరీ చిరునామా అవసరం. ముందు కొత్తది జోడించి, తర్వాత ఇది తొలగించండి.',
  address_delete_title:         'చిరునామా తొలగించు',
  address_delete_confirm:       'తొలగించు',
  address_cancel:               'రద్దు చేయి',
  address_ok:                   'సరే',

  // ─── Address Form screen ──────────────────────────────────────────
  address_form_title_add:       'చిరునామా జోడించు',
  address_form_title_edit:      'చిరునామా సవరించు',
  address_form_name:            'పూర్తి పేరు',
  address_form_phone:           'ఫోన్ నంబర్',
  address_form_line1:           'చిరునామా వరుస 1',
  address_form_line2:           'చిరునామా వరుస 2 (ఐచ్ఛికం)',
  address_form_city:            'నగరం / పట్టణం',
  address_form_district:        'జిల్లా',
  address_form_state:           'రాష్ట్రం',
  address_form_pincode:         'పిన్‌కోడ్',
  address_form_label:           'లేబుల్',
  address_form_save:            'చిరునామా సేవ్ చేయి',
  address_form_update:          'చిరునామా అప్‌డేట్ చేయి',

  // ─── Favorites screen ─────────────────────────────────────────────
  favorites_title:              'నా విష్‌లిస్ట్',
  favorites_loading:            'లోడ్ అవుతోంది…',
  favorites_empty_title:        'మీ విష్‌లిస్ట్ ఖాళీగా ఉంది',
  favorites_empty_sub:          'మీకు నచ్చిన ఉత్పత్తులపై హార్ట్ చిహ్నం నొక్కండి',
  favorites_explore:            'ఉత్పత్తులు అన్వేషించండి →',
  favorites_item:               'వస్తువు',
  favorites_items:              'వస్తువులు',

  // ─── Location Picker screen ───────────────────────────────────────
  location_title:               'స్థానం ఎంచుకోండి',
  location_search_placeholder:  'మీ ప్రాంతం లేదా పిన్‌కోడ్ వెతకండి…',
  location_detecting:           'మీ స్థానం గుర్తిస్తోంది…',
  location_detect_gps:          'ప్రస్తుత స్థానం ఉపయోగించు',
  location_suggestions:         'సూచనలు',
  location_recent:              'ఇటీవలి',
  location_select:              'ఎంచుకోండి',

  // ─── Payments screen ──────────────────────────────────────────────
  payments_title:               'పేమెంట్ పద్ధతులు',
  payments_back:                '← వెనక్కి',
  payments_upi_section:         'UPI IDలు',
  payments_card_section:        'కార్డులు',
  payments_add_upi:             'UPI ID జోడించు',
  payments_add_card:            'కార్డు జోడించు',
  payments_no_upi:              'UPI IDలు సేవ్ చేయలేదు',
  payments_no_cards:            'కార్డులు సేవ్ చేయలేదు',
  payments_default:             'డిఫాల్ట్',
  payments_set_default:         'డిఫాల్ట్ సెట్ చేయి',
  payments_remove:              'తొలగించు',

  // ─── Wallet screen ────────────────────────────────────────────────
  wallet_title:                 'హార్వెస్ట్ వాలెట్',
  wallet_back:                  '← వెనక్కి',
  wallet_balance_label:         'అందుబాటులో ఉన్న బ్యాలెన్స్',
  wallet_balance_sub:           'తక్షణ పేమెంట్ కోసం చెక్‌అవుట్‌లో ఉపయోగించండి',
  wallet_add_money:             '+ డబ్బు జోడించు',
  wallet_form_title:            'వాలెట్‌కు డబ్బు జోడించు',
  wallet_select_amount:         'మొత్తం ఎంచుకోండి',
  wallet_custom_or:             '— లేదా కస్టమ్ మొత్తం నమోదు చేయండి —',
  wallet_pay_via:               'ద్వారా చెల్లించు',
  wallet_no_pm:                 'పేమెంట్ పద్ధతులు సేవ్ చేయలేదు — UPI లేదా కార్డు జోడించండి',
  wallet_cancel:                'రద్దు చేయి',
  wallet_confirm_add:           'జోడించు',
  wallet_preview_adding:        'జోడిస్తోంది',
  wallet_preview_to:            'వాలెట్‌కు',
  wallet_preview_new_bal:       'కొత్త బ్యాలెన్స్',
  wallet_transactions:          'లావాదేవీ చరిత్ర',
  wallet_empty:                 'ఇంకా లావాదేవీలు లేవు',
  wallet_empty_sub:             'ప్రారంభించడానికి డబ్బు జోడించండి',
  wallet_info:                  'వాలెట్ బ్యాలెన్స్ చెక్‌అవుట్‌లో ఉపయోగించవచ్చు. గరిష్ట వాలెట్ బ్యాలెన్స్ ₹10,000. ఉపయోగించని బ్యాలెన్స్ ఎప్పటికీ పోదు.',
  wallet_added_title:           'డబ్బు జోడించబడింది!',
  wallet_added_msg:             'మీ హార్వెస్ట్ వాలెట్‌కు జోడించబడింది.',
  wallet_min_error:             'కనీస మొత్తం ₹1',
  wallet_max_error:             'లావాదేవీకి గరిష్టం ₹10,000',
  wallet_pm_error:              'పేమెంట్ పద్ధతి ఎంచుకోండి',

  // ─── Referral screen ──────────────────────────────────────────────
  referral_title:               'రెఫర్ & సంపాదించండి',
  referral_back:                '←',
  referral_hero_title:          'స్నేహితులను ఆహ్వానించండి,\nరివార్డులు సంపాదించండి',
  referral_hero_sub:            'మొదటి ఆర్డర్ పెట్టిన ప్రతి స్నేహితుడికి మీకు ₹100 వస్తుంది.\nవారికి మొదటి ఆర్డర్‌పై ₹50 తగ్గింపు వస్తుంది.',
  referral_code_label:          'మీ రెఫరల్ కోడ్',
  referral_copy:                'కాపీ చేయి',
  referral_copied:              '✓ కాపీ అయింది',
  referral_share:               'స్నేహితులతో పంచుకోండి ↗',
  referral_friends_invited:     'ఆహ్వానించిన స్నేహితులు',
  referral_orders_placed:       'పెట్టిన ఆర్డర్లు',
  referral_total_earned:        'మొత్తం సంపాదించింది',
  referral_your_referrals:      'మీ రెఫరల్లు',
  referral_rewarded:            'స్నేహితుడు మొదటి ఆర్డర్ పెట్టాడు',
  referral_awaiting:            'స్నేహితుడు రిజిస్టర్ అయ్యాడు — మొదటి ఆర్డర్ వేచి ఉంది',
  referral_pending:             'పెండింగ్‌లో ఉంది',
  referral_how_title:           'ఇది ఎలా పనిచేస్తుంది',
  referral_step1_title:         'మీ కోడ్ పంచుకోండి',
  referral_step1_desc:          'WhatsApp, SMS లేదా ఏదైనా యాప్ ద్వారా మీ కోడ్ పంపండి.',
  referral_step2_title:         'స్నేహితుడు నమోదు అవుతాడు',
  referral_step2_desc:          'వారు రిజిస్ట్రేషన్ సమయంలో మీ కోడ్ నమోదు చేసి ₹50 తగ్గింపు పొందుతారు.',
  referral_step3_title:         'స్నేహితుడు మొదటి ఆర్డర్ పెడతాడు',
  referral_step3_desc:          'వారి మొదటి ఆర్డర్ డెలివరీ అయిన తర్వాత, మీ హార్వెస్ట్ వాలెట్‌కు ₹100 జమ అవుతుంది.',
  referral_terms_1:             'స్నేహితుడి మొదటి ఆర్డర్ డెలివరీ తర్వాత రెఫరల్ రివార్డ్ జమ అవుతుంది',
  referral_terms_2:             'స్నేహితుడు కొత్త వినియోగదారు అయి ఉండాలి',
  referral_terms_3:             'ఒక ఖాతాకు ఒక రెఫరల్ కోడ్',
  referral_terms_4:             'ప్రతి వినియోగదారుకు నెలకు గరిష్టం 10 రెఫరల్లు',

  // ─── Search screen ────────────────────────────────────────────────
  search_placeholder:           'కూరగాయలు, చేనేత, మసాలాలు వెతకండి...',
  search_results:               'ఫలితాలు',
  search_result_count:          'ఉత్పత్తులు కనుగొనబడ్డాయి',
  search_no_results:            'ఫలితాలు కనుగొనబడలేదు',
  search_no_results_sub:        'వేరే పదం ప్రయత్నించండి లేదా వర్గాలు బ్రౌజ్ చేయండి',
  search_recent:                'ఇటీవలి శోధనలు',
  search_clear:                 'తీసివేయి',

  // ─── Vendors screen ───────────────────────────────────────────────
  vendors_title:                'స్థానిక విక్రేతలు',
  vendors_back:                 '← వెనక్కి',
  vendors_count:                'దగ్గర్లో విక్రేతలు',
  vendors_empty:                'మీ ప్రాంతంలో విక్రేతలు కనుగొనబడలేదు',
  vendors_empty_sub:            'మీ శోధన ప్రాంతాన్ని విస్తరించండి',
  vendors_visit:                'షాప్ సందర్శించండి →',
};

const HI: typeof EN = {
  // ─── Settings modal ───────────────────────────────────────────────
  settings_title:               'ऐप सेटिंग्स',
  settings_notifications:       'सूचनाएं',
  notif_order_updates:          'ऑर्डर स्टेटस अपडेट',
  notif_order_updates_desc:     'दिया गया → भेजा गया → डिलीवरी में → पहुंचा',
  notif_price_drops:            'कीमत गिरने की सूचना',
  notif_price_drops_desc:       'विशलिस्ट आइटम की कीमत गिरने पर अलर्ट',
  notif_new_arrivals:           'पास में नई चीज़ें',
  notif_new_arrivals_desc:      'आपके इलाके के विक्रेताओं के ताज़े उत्पाद',
  notif_promos:                 'ऑफर और प्रमोशन',
  notif_promos_desc:            'छूट, कैशबैक और सीज़नल डील्स',
  settings_display:             'डिस्प्ले',
  display_language:             'भाषा',
  display_dark_mode:            'रूप',
  display_dark_mode_desc:       'अपना पसंदीदा थीम चुनें',
  theme_light:                  'लाइट',
  theme_dark:                   'डार्क',
  theme_system:                 'सिस्टम',
  settings_shopping:            'शॉपिंग प्राथमिकताएं',
  shop_wallet_auto:             'वॉलेट अपने आप लगाएं',
  shop_wallet_auto_desc:        'चेकआउट पर वॉलेट बैलेंस अपने आप इस्तेमाल करें',
  shop_gst_inclusive:           'GST सहित कीमत दिखाएं',
  shop_gst_inclusive_desc:      'सभी करों सहित अंतिम कीमत दिखाएं',
  settings_privacy:             'गोपनीयता और कानूनी',
  privacy_policy:               'गोपनीयता नीति',
  terms_of_service:             'सेवा की शर्तें',
  data_permissions:             'डेटा और अनुमतियां',
  settings_about:               'ऐप के बारे में',
  about_version:                'ऐप वर्शन',
  about_rate_app:               'HarvestConnect को रेट करें',
  about_rate_app_desc:          'ऐप पसंद आया? हमें रिव्यू दें',

  // ─── Help & Support ───────────────────────────────────────────────
  help_title:                   'सहायता और समर्थन',
  help_hint:                    'नीचे सामान्य प्रश्न हैं। विस्तार के लिए टैप करें।',
  help_faqs:                    'अक्सर पूछे जाने वाले प्रश्न',
  help_faq_q1:                  'मैं अपना ऑर्डर कैसे ट्रैक करूं?',
  help_faq_a1:                  'Orders टैब → अपना ऑर्डर टैप करें → डिस्पैच से डिलीवरी तक रियल-टाइम स्टेटस देखें।',
  help_faq_q2:                  'ऑर्डर कैसे रद्द करें?',
  help_faq_a2:                  'विक्रेता के भेजने से पहले रद्द किया जा सकता है। Orders → ऑर्डर टैप करें → Cancel करें।',
  help_faq_q3:                  'कौन से पेमेंट तरीके उपलब्ध हैं?',
  help_faq_a3:                  'UPI (GPay, PhonePe, Paytm), डेबिट/क्रेडिट कार्ड और Harvest Wallet स्वीकार किए जाते हैं।',
  help_faq_q4:                  'Harvest Wallet कैसे काम करता है?',
  help_faq_a4:                  'रिफंड और रेफरल रिवॉर्ड से वॉलेट में पैसे आते हैं। चेकआउट पर पूरा या आंशिक भुगतान कर सकते हैं।',
  help_faq_q5:                  'रिफंड कैसे मांगें?',
  help_faq_a5:                  'गलत या क्षतिग्रस्त सामान मिलने पर डिलीवरी के 24 घंटे के भीतर Orders → Issue with Order से अनुरोध करें।',
  help_faq_q6:                  'ऑर्डर के बाद डिलीवरी पता बदल सकते हैं?',
  help_faq_a6:                  'विक्रेता के स्वीकार करने से पहले बदला जा सकता है। WhatsApp पर तुरंत संपर्क करें।',
  help_faq_q7:                  'HarvestConnect कहाँ डिलीवरी करता है?',
  help_faq_a7:                  'फिलहाल निज़ामाबाद, आर्मूर, बंसवाड़ा, कामारेड्डी और आसपास के क्षेत्रों में सेवा उपलब्ध है।',
  help_faq_q8:                  'विक्रेता से सीधे कैसे संपर्क करें?',
  help_faq_a8:                  'ऑर्डर कन्फर्म होने के बाद Order Details स्क्रीन पर विक्रेता का संपर्क दिखेगा।',
  help_contact:                 'सहायता से संपर्क करें',
  help_call:                    'कॉल करें',
  help_call_hours:              'सोम–शनि, सुबह 9 – शाम 6',
  help_whatsapp:                'WhatsApp',
  help_whatsapp_sub:            'सबसे तेज़ जवाब',
  help_email:                   'ईमेल',
  help_email_sub:               '24 घंटे में जवाब',
  help_guide:                   'खरीदार गाइड',
  help_guide_sub:               'ऑर्डर, ट्रैकिंग और बेहतरीन डील्स के टिप्स',

  // ─── Home screen ──────────────────────────────────────────────────
  home_brand_name:              'Harvest Connect',
  home_tagline:                 'स्थानीय खजाने, डिलीवरी के साथ',
  home_search_placeholder:      'सब्ज़ियां, हथकरघा, मसाले खोजें...',
  home_delivering_to:           'डिलीवरी हो रही है',
  home_trust_title:             'सत्यापित स्थानीय विक्रेता',
  home_trust_sub:               'सरकारी ID और गुणवत्ता जांच',
  home_trust_count:             '2,340+',
  home_shop_by_category:        'श्रेणी से खरीदें',
  home_view_all:                'सभी देखें ›',
  home_near_mandal:             'आपके मंडल के पास',
  home_see_all:                 'सभी देखें ›',
  home_featured_products:       'फीचर्ड उत्पाद',
  home_visit_shop:              'दुकान देखें →',
  home_items:                   'आइटम',
  home_banner_badge:            'तेलंगाना स्पेशल',
  home_banner_title:            'असली तेलंगाना\nशिल्पकला खोजें',
  home_banner_sub:              'बीदरी काम, निर्मल पेंटिंग और भी',
  home_banner_btn:              'अभी खोजें →',

  // ─── Explore screen ───────────────────────────────────────────────
  explore_title:                'उत्पाद खोजें',
  explore_search_placeholder:   'उत्पाद, विक्रेता खोजें...',
  explore_region_label:         'क्षेत्र से खरीदें',
  explore_sort_by:              'क्रमबद्ध करें ▾',
  explore_loading:              'लोड हो रहा है…',
  explore_products_in:          'उत्पाद',
  explore_empty_title:          'इस क्षेत्र में अभी उत्पाद नहीं हैं',
  explore_empty_sub:            'विक्रेता जुड़ रहे हैं — दूसरा क्षेत्र देखें या बाद में आएं!',
  explore_hyperlocal:           'हाइपरलोकल',
  explore_district:             'जिला',
  explore_state:                'राज्य',
  explore_nationwide:           'राष्ट्रव्यापी',
  explore_nearby:               'पास में',
  explore_all_india:            'अखिल भारत',

  // ─── Cart screen ──────────────────────────────────────────────────
  cart_title:                   'शॉपिंग कार्ट',
  cart_empty_title:             'आपकी कार्ट खाली है',
  cart_empty_desc:              'शुरू करने के लिए Home या Explore से उत्पाद जोड़ें।',
  cart_delivering_to:           'डिलीवरी हो रही है',
  cart_change:                  'बदलें ›',
  cart_no_address:              'डिलीवरी पता जोड़ने के लिए टैप करें',
  cart_select_all:              'सभी चुनें',
  cart_deselect_all:            'सभी हटाएं',
  cart_selected_of:             'में से',
  cart_selected:                'चुने गए',
  cart_coupon_placeholder:      'कूपन कोड दर्ज करें',
  cart_apply:                   'लागू करें',
  cart_price_details:           'कीमत विवरण',
  cart_subtotal:                'उप-कुल',
  cart_delivery_fee:            'डिलीवरी शुल्क',
  cart_coupon_discount:         'कूपन छूट',
  cart_total_payable:           'कुल देय',
  cart_select_to_continue:      'जारी रखने के लिए आइटम चुनें',
  cart_proceed_checkout:        'चेकआउट पर जाएं →',
  cart_terms:                   'ऑर्डर देकर आप हमारी शर्तों से सहमत हैं',

  // ─── Orders screen ────────────────────────────────────────────────
  orders_title:                 'मेरे ऑर्डर',
  orders_subtitle:              'अपनी खरीदारी ट्रैक करें',
  orders_tab_all:               'सभी',
  orders_tab_active:            'सक्रिय',
  orders_tab_delivered:         'डिलीवर',
  orders_tab_cancelled:         'रद्द किए गए',
  orders_empty_title:           'अभी कोई ऑर्डर नहीं',
  orders_empty_sub_all:         'आपने अभी तक कोई ऑर्डर नहीं दिया। खोजना शुरू करें!',
  orders_empty_sub_filter:      'ऑर्डर यहाँ दिखेंगे।',
  orders_status_delivered:      'डिलीवर',
  orders_status_transit:        'रास्ते में',
  orders_status_processing:     'प्रोसेसिंग',
  orders_status_cancelled:      'रद्द किया गया',
  orders_expected_by:           'अपेक्षित',
  orders_total:                 'ऑर्डर कुल',
  orders_support:               '💬 सहायता',
  orders_track:                 'ट्रैक →',

  // ─── Profile screen ───────────────────────────────────────────────
  profile_loading:              'प्रोफ़ाइल लोड हो रही है…',
  profile_member_since:         'सदस्य',
  profile_orders:               'ऑर्डर',
  profile_wishlist:             'विशलिस्ट',
  profile_wallet:               'वॉलेट',
  profile_in_cart:              'कार्ट में',
  profile_location_title:       'आपका स्थान',
  profile_detect:               '⟳ पता करें',
  profile_detecting:            '…',
  profile_open_settings:        'सेटिंग्स खोलें →',
  profile_manual_placeholder:   'अपना इलाका या शहर लिखें…',
  profile_save:                 'सेव करें',
  profile_sign_out:             '🚪  साइन आउट',
  profile_total:                'कुल',
  profile_items:                'आइटम',

  menu_my_orders:               'मेरे ऑर्डर',
  menu_my_orders_desc:          'अपनी खरीदारी ट्रैक करें',
  menu_wishlist:                'विशलिस्ट',
  menu_wishlist_desc:           'आपकी सहेजी गई चीज़ें',
  menu_saved_addresses:         'सहेजे गए पते',
  menu_saved_addresses_desc:    'डिलीवरी स्थान प्रबंधित करें',
  menu_payment_methods:         'पेमेंट के तरीके',
  menu_payment_methods_desc:    'कार्ड और UPI',
  menu_wallet:                  'हार्वेस्ट वॉलेट',
  menu_wallet_desc:             'आपका बैलेंस',
  menu_refer_earn:              'रेफर और कमाएं',
  menu_refer_earn_desc:         'प्रति रेफरल ₹100 पाएं',
  menu_become_seller:           'विक्रेता बनें',
  menu_become_seller_desc:      'अपना स्थानीय व्यवसाय शुरू करें',
  menu_settings:                'सेटिंग्स',
  menu_settings_desc:           'ऐप प्राथमिकताएं',
  menu_help:                    'सहायता और समर्थन',
  menu_help_desc:               'FAQs और संपर्क',

  // ─── Login screen ─────────────────────────────────────────────────
  login_app_name:               'Harvest Connect',
  login_hero_tagline:           'खेत से ताज़ा, सीधे आपके दरवाज़े',
  login_welcome:                'वापस स्वागत है 👋',
  login_card_sub:               'जारी रखने के लिए अपना फ़ोन नंबर दर्ज करें',
  login_secure_otp:             '🔒  सुरक्षित OTP',
  login_instant:                '⚡  तुरंत लॉगिन',
  login_phone_label:            'मोबाइल नंबर',
  login_phone_placeholder:      '+91 XXXXX XXXXX',
  login_send_otp:               'OTP भेजें →',
  login_new_to:                 'HarvestConnect पर नए हैं?',
  login_create_account:         'अकाउंट बनाएं',
  login_trusted_by:             'भरोसा करते हैं',
  login_trusted_suffix:         'तेलंगाना में खरीदार',

  // ─── OTP screen ───────────────────────────────────────────────────
  otp_heading:                  'अपना नंबर सत्यापित करें',
  otp_sub:                      '6-अंकीय कोड भेजा गया',
  otp_verifying:                'सत्यापित हो रहा है…',
  otp_resend:                   'OTP फिर भेजें',
  otp_resend_in:                'OTP फिर भेजें',
  otp_badge_register:           '🆕  रजिस्ट्रेशन OTP',
  otp_badge_login:              '🔐  लॉगिन OTP',
  otp_tip_register:             '💡  अगर ईमेल जोड़ी है, तो इनबॉक्स भी देखें — कोड वहाँ भी भेजा है',
  otp_tip_login:                '💡  नहीं मिला? SMS देखें और फिर भेजने से पहले कुछ देर रुकें',
  otp_back:                     'वापस',

  // ─── Register screen ──────────────────────────────────────────────
  register_hero_tagline:        'स्थानीय किसानों और कारीगरों से जुड़ें',
  register_benefit_free:        'मुफ़्त जुड़ें',
  register_benefit_local:       'सत्यापित स्थानीय',
  register_benefit_delivery:    'तेज़ डिलीवरी',
  register_title:               'अकाउंट बनाएं',
  register_sub:                 '2,340+ खरीदारों से जुड़ें। एक मिनट से कम।',
  register_name_label:          'पूरा नाम',
  register_name_placeholder:    'अपना पूरा नाम दर्ज करें',
  register_phone_label:         'मोबाइल नंबर',
  register_email_label:         'ईमेल',
  register_email_optional:      'वैकल्पिक · OTP के लिए',
  register_referral_label:      'रेफरल कोड',
  register_referral_optional:   'वैकल्पिक · पहले ऑर्डर पर ₹50 की छूट',
  register_create_btn:          'अकाउंट बनाएं →',
  register_note:                '📲  आपका मोबाइल नंबर सत्यापित करने के लिए 6-अंकीय OTP भेजेंगे',
  register_already:             'पहले से सदस्य हैं?',
  register_login_instead:       'लॉगिन करें',

  // ─── Checkout screen ──────────────────────────────────────────────
  checkout_title:               'चेकआउट',
  checkout_back:                '← वापस',
  checkout_deliver_to:          'डिलीवरी करें',
  checkout_delivery_slot:       'डिलीवरी स्लॉट',
  checkout_payment_method:      'पेमेंट का तरीका',
  checkout_order_summary:       'ऑर्डर सारांश',
  checkout_change:              'बदलें ›',
  checkout_default:             'डिफ़ॉल्ट',
  checkout_subtotal:            'उप-कुल',
  checkout_delivery_fee:        'डिलीवरी शुल्क',
  checkout_coupon_discount:     'कूपन छूट',
  checkout_total:               'कुल देय',
  checkout_place_order:         'ऑर्डर दें',
  checkout_items_from:          'आइटम',
  checkout_vendor:              'विक्रेता',
  checkout_vendors:             'विक्रेता',
  checkout_slot_today:          'आज',
  checkout_slot_today_sub:      'शाम 4 – 6',
  checkout_slot_tomorrow:       'कल',
  checkout_slot_tomorrow_sub:   'दोपहर 12 से पहले',
  checkout_slot_schedule:       'शेड्यूल',
  checkout_slot_schedule_sub:   'तारीख चुनें',
  checkout_cod:                 'डिलीवरी पर भुगतान',
  checkout_wallet_empty:        'बैलेंस नहीं — पहले पैसे जोड़ें',
  checkout_please_login:        'जारी रखने के लिए लॉगिन करें।',

  // ─── Order Confirmed screen ────────────────────────────────────────
  order_confirmed_title:        'ऑर्डर दिया! 🎉',
  order_confirmed_sub:          'आपका ऑर्डर सफलतापूर्वक दिया गया।',
  order_confirmed_id:           'ऑर्डर ID',
  order_confirmed_slot:         'डिलीवरी स्लॉट',
  order_confirmed_payment:      'पेमेंट',
  order_confirmed_track:        'मेरा ऑर्डर ट्रैक करें',
  order_confirmed_continue:     'खरीदारी जारी रखें',

  // ─── Order Detail screen ──────────────────────────────────────────
  order_detail_title:           'ऑर्डर विवरण',
  order_detail_back:            '← वापस',
  order_detail_timeline:        'ऑर्डर टाइमलाइन',
  order_detail_placed:          'ऑर्डर दिया',
  order_detail_confirmed:       'कन्फर्म हुआ',
  order_detail_dispatched:      'भेजा गया',
  order_detail_transit:         'रास्ते में',
  order_detail_delivered:       'पहुंचा',
  order_detail_items:           'आइटम',
  order_detail_summary:         'कीमत सारांश',
  order_detail_subtotal:        'उप-कुल',
  order_detail_delivery:        'डिलीवरी शुल्क',
  order_detail_discount:        'छूट',
  order_detail_total:           'कुल भुगतान',

  // ─── Product Detail screen ────────────────────────────────────────
  product_back:                 '← वापस',
  product_add_to_cart:          'कार्ट में जोड़ें',
  product_add_more:             '+ और जोड़ें',
  product_in_cart:              'कार्ट में है',
  product_about:                'इस उत्पाद के बारे में',
  product_vendor:               'विक्रेता',
  product_visit_shop:           'दुकान देखें →',
  product_rating:               'रेटिंग और समीक्षाएं',

  // ─── Vendor screen ────────────────────────────────────────────────
  vendor_back:                  '← वापस',
  vendor_products:              'उत्पाद',
  vendor_rating:                'रेटिंग',
  vendor_distance:              'दूरी',
  vendor_items:                 'आइटम',
  vendor_empty:                 'इस विक्रेता के अभी कोई उत्पाद नहीं',

  // ─── Category screen ──────────────────────────────────────────────
  category_back:                '← वापस',
  category_products:            'उत्पाद',
  category_empty:               'इस श्रेणी में अभी उत्पाद नहीं हैं',
  category_empty_sub:           'जल्द आएंगे — विक्रेता उत्पाद जोड़ रहे हैं!',

  // ─── Address Book screen ──────────────────────────────────────────
  address_book_title:           'सहेजे गए पते',
  address_select_title:         'पता चुनें',
  address_back:                 '← वापस',
  address_empty_title:          'कोई पता नहीं',
  address_empty_sub:            'शुरू करने के लिए डिलीवरी पता जोड़ें।',
  address_add:                  '+ नया पता जोड़ें',
  address_default:              'डिफ़ॉल्ट',
  address_set_default:          'डिफ़ॉल्ट बनाएं',
  address_edit:                 'संपादित करें',
  address_delete:               'हटाएं',
  address_cannot_delete_title:  'हटा नहीं सकते',
  address_cannot_delete_msg:    'कम से कम एक डिलीवरी पता ज़रूरी है। पहले नया जोड़ें, फिर इसे हटाएं।',
  address_delete_title:         'पता हटाएं',
  address_delete_confirm:       'हटाएं',
  address_cancel:               'रद्द करें',
  address_ok:                   'ठीक है',

  // ─── Address Form screen ──────────────────────────────────────────
  address_form_title_add:       'पता जोड़ें',
  address_form_title_edit:      'पता संपादित करें',
  address_form_name:            'पूरा नाम',
  address_form_phone:           'फ़ोन नंबर',
  address_form_line1:           'पता लाइन 1',
  address_form_line2:           'पता लाइन 2 (वैकल्पिक)',
  address_form_city:            'शहर / कस्बा',
  address_form_district:        'जिला',
  address_form_state:           'राज्य',
  address_form_pincode:         'पिनकोड',
  address_form_label:           'लेबल',
  address_form_save:            'पता सेव करें',
  address_form_update:          'पता अपडेट करें',

  // ─── Favorites screen ─────────────────────────────────────────────
  favorites_title:              'मेरी विशलिस्ट',
  favorites_loading:            'लोड हो रहा है…',
  favorites_empty_title:        'आपकी विशलिस्ट खाली है',
  favorites_empty_sub:          'किसी भी उत्पाद पर दिल का निशान टैप करें',
  favorites_explore:            'उत्पाद खोजें →',
  favorites_item:               'आइटम',
  favorites_items:              'आइटम',

  // ─── Location Picker screen ───────────────────────────────────────
  location_title:               'स्थान चुनें',
  location_search_placeholder:  'अपना इलाका या पिनकोड खोजें…',
  location_detecting:           'आपका स्थान पता कर रहे हैं…',
  location_detect_gps:          'वर्तमान स्थान उपयोग करें',
  location_suggestions:         'सुझाव',
  location_recent:              'हाल के',
  location_select:              'चुनें',

  // ─── Payments screen ──────────────────────────────────────────────
  payments_title:               'पेमेंट के तरीके',
  payments_back:                '← वापस',
  payments_upi_section:         'UPI IDs',
  payments_card_section:        'कार्ड',
  payments_add_upi:             'UPI ID जोड़ें',
  payments_add_card:            'कार्ड जोड़ें',
  payments_no_upi:              'कोई UPI ID नहीं',
  payments_no_cards:            'कोई कार्ड नहीं',
  payments_default:             'डिफ़ॉल्ट',
  payments_set_default:         'डिफ़ॉल्ट बनाएं',
  payments_remove:              'हटाएं',

  // ─── Wallet screen ────────────────────────────────────────────────
  wallet_title:                 'हार्वेस्ट वॉलेट',
  wallet_back:                  '← वापस',
  wallet_balance_label:         'उपलब्ध बैलेंस',
  wallet_balance_sub:           'चेकआउट पर तुरंत भुगतान के लिए उपयोग करें',
  wallet_add_money:             '+ पैसे जोड़ें',
  wallet_form_title:            'वॉलेट में पैसे जोड़ें',
  wallet_select_amount:         'राशि चुनें',
  wallet_custom_or:             '— या कस्टम राशि दर्ज करें —',
  wallet_pay_via:               'द्वारा भुगतान',
  wallet_no_pm:                 'कोई पेमेंट तरीका नहीं — UPI या कार्ड जोड़ें',
  wallet_cancel:                'रद्द करें',
  wallet_confirm_add:           'जोड़ें',
  wallet_preview_adding:        'जोड़ रहे हैं',
  wallet_preview_to:            'वॉलेट में',
  wallet_preview_new_bal:       'नया बैलेंस होगा',
  wallet_transactions:          'लेन-देन इतिहास',
  wallet_empty:                 'अभी कोई लेन-देन नहीं',
  wallet_empty_sub:             'शुरू करने के लिए पैसे जोड़ें',
  wallet_info:                  'वॉलेट बैलेंस चेकआउट पर उपयोग किया जा सकता है। अधिकतम वॉलेट बैलेंस ₹10,000 है। अप्रयुक्त बैलेंस कभी समाप्त नहीं होता।',
  wallet_added_title:           'पैसे जुड़ गए!',
  wallet_added_msg:             'आपके हार्वेस्ट वॉलेट में जुड़ गए।',
  wallet_min_error:             'न्यूनतम राशि ₹1',
  wallet_max_error:             'प्रति लेन-देन अधिकतम ₹10,000',
  wallet_pm_error:              'पेमेंट का तरीका चुनें',

  // ─── Referral screen ──────────────────────────────────────────────
  referral_title:               'रेफर और कमाएं',
  referral_back:                '←',
  referral_hero_title:          'दोस्तों को बुलाएं,\nइनाम कमाएं',
  referral_hero_sub:            'हर दोस्त के पहले ऑर्डर पर आपको ₹100 मिलते हैं।\nउन्हें पहले ऑर्डर पर ₹50 की छूट मिलती है।',
  referral_code_label:          'आपका रेफरल कोड',
  referral_copy:                'कॉपी करें',
  referral_copied:              '✓ कॉपी हुआ',
  referral_share:               'दोस्तों के साथ शेयर करें ↗',
  referral_friends_invited:     'आमंत्रित दोस्त',
  referral_orders_placed:       'दिए गए ऑर्डर',
  referral_total_earned:        'कुल कमाई',
  referral_your_referrals:      'आपके रेफरल',
  referral_rewarded:            'दोस्त ने पहला ऑर्डर दिया',
  referral_awaiting:            'दोस्त जुड़ गया — पहले ऑर्डर का इंतज़ार',
  referral_pending:             'लंबित',
  referral_how_title:           'यह कैसे काम करता है',
  referral_step1_title:         'कोड शेयर करें',
  referral_step1_desc:          'WhatsApp, SMS या किसी भी ऐप से दोस्तों को कोड भेजें।',
  referral_step2_title:         'दोस्त जुड़ता है',
  referral_step2_desc:          'वे रजिस्ट्रेशन में कोड डालते हैं और ₹50 की छूट पाते हैं।',
  referral_step3_title:         'दोस्त पहला ऑर्डर देता है',
  referral_step3_desc:          'पहला ऑर्डर डिलीवर होने पर आपके हार्वेस्ट वॉलेट में ₹100 जुड़ते हैं।',
  referral_terms_1:             'दोस्त के पहले ऑर्डर की डिलीवरी के बाद रेफरल इनाम मिलता है',
  referral_terms_2:             'दोस्त नया उपयोगकर्ता होना चाहिए',
  referral_terms_3:             'प्रति खाता एक रेफरल कोड',
  referral_terms_4:             'प्रति उपयोगकर्ता प्रति माह अधिकतम 10 रेफरल',

  // ─── Search screen ────────────────────────────────────────────────
  search_placeholder:           'सब्ज़ियां, हथकरघा, मसाले खोजें...',
  search_results:               'परिणाम',
  search_result_count:          'उत्पाद मिले',
  search_no_results:            'कोई परिणाम नहीं',
  search_no_results_sub:        'दूसरा शब्द आज़माएं या श्रेणियां देखें',
  search_recent:                'हाल की खोजें',
  search_clear:                 'साफ़ करें',

  // ─── Vendors screen ───────────────────────────────────────────────
  vendors_title:                'स्थानीय विक्रेता',
  vendors_back:                 '← वापस',
  vendors_count:                'पास में विक्रेता',
  vendors_empty:                'आपके इलाके में कोई विक्रेता नहीं मिला',
  vendors_empty_sub:            'खोज क्षेत्र बढ़ाएं',
  vendors_visit:                'दुकान देखें →',
};

const TRANSLATIONS: Record<Language, typeof EN> = { en: EN, te: TE, hi: HI };

export type TranslationKey = keyof typeof EN;

interface LanguageContextValue {
  language: Language;
  setLanguage: (l: Language) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY)
      .then((stored) => {
        if (stored === 'en' || stored === 'te' || stored === 'hi') {
          setLanguageState(stored);
        }
      })
      .catch(() => {});
  }, []);

  function setLanguage(l: Language) {
    setLanguageState(l);
    AsyncStorage.setItem(STORAGE_KEY, l).catch(() => {});
  }

  function t(key: TranslationKey): string {
    return TRANSLATIONS[language][key] ?? TRANSLATIONS.en[key] ?? key;
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
